version: '3.4'
services:
  db:
    image: mysql:5.6
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: catsdb
    ports:
      - "3308:3306"
    networks:
      - itau-network

  cats-api-collector:
    image: cats-api-collector
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      TZ: America/Sao_Paulo
    ports:
      - "8080:8080"
    command: mvn spring-boot:run
    links:
      - db
    depends_on:
      - db
    networks:
      - itau-network

networks:
  itau-network:
    driver: bridge